### ISSUE TITLE
`.map(await(_))` does not compile with generic type parameter

### ISSUE THREAD

**Issue by armanbilge** [rssh/dotty-cps-async#63]
```scala
//> using lib "com.github.rssh::dotty-cps-async::0.9.12"

import cps.*
import cps.monads.{*, given}

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

// if `A` is replaced with concrete type it compiles
def futureFetchList[A](l: List[Future[A]]): Future[List[A]] =
  async[Future] {
    l.map(await(_))
  }
```

```
$ scala-cli test.scala 
Compiling project (Scala 3.2.1, JVM)
[error] ./test.scala:10:3: Exception occurred while executing macro expansion.
[error] java.lang.Exception: Expr cast exception: _$1
[error] of type: _$1
[error] did not conform to type: scala.concurrent.Future[scala.concurrent.Future[scala.Nothing]]
[error] 
[error]         at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:73)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:116)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:115)
[error]         at cps.macros.forest.application.ApplyArgRecordScope$ApplyArgLambdaRecord.$anonfun$8(ApplyArgRecordScope.scala:260)
[error]         at cps.macros.forest.application.ApplyArgRecordScope$ApplyArgLambdaRecord.$anonfun$adapted$1(ApplyArgRecordScope.scala:260)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:109)
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1446)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:134)
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1507)
[error]         at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1507)
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1412)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:134)
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1412)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:134)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:151)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:87)
[error]         at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3044)
[error]         at cps.macros.forest.application.ApplyArgRecordScope$ApplyArgLambdaRecord.identArg(ApplyArgRecordScope.scala:260)
[error]         at cps.macros.forest.ApplyTreeTransform.$anonfun$7(ApplyTreeTransform.scala:642)
[error]         at scala.collection.immutable.List.map(List.scala:246)
[error]         at scala.collection.immutable.List.map(List.scala:79)
[error]         at cps.macros.forest.ApplyTreeTransform.buildApply(ApplyTreeTransform.scala:642)
[error]         at cps.macros.forest.ApplyTreeTransform.buildApply$(ApplyTreeTransform.scala:12)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.buildApply(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.ApplyTreeTransform.handleArgs1(ApplyTreeTransform.scala:314)
[error]         at cps.macros.forest.ApplyTreeTransform.handleArgs1$(ApplyTreeTransform.scala:12)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.handleArgs1(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.ApplyTreeTransform.handleFunTypeApply(ApplyTreeTransform.scala:123)
[error]         at cps.macros.forest.ApplyTreeTransform.handleFunTypeApply$(ApplyTreeTransform.scala:12)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.handleFunTypeApply(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.ApplyTreeTransform.runApply(ApplyTreeTransform.scala:35)
[error]         at cps.macros.forest.ApplyTreeTransform.runApply$(ApplyTreeTransform.scala:12)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.runApply(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.RootTreeTransform.$anonfun$2(RootTreeTransform.scala:47)
[error]         at cps.macros.forest.RootTreeTransform$B2$.inNestedContext(RootTreeTransform.scala:161)
[error]         at cps.macros.forest.RootTreeTransform.runRoot(RootTreeTransform.scala:47)
[error]         at cps.macros.forest.RootTreeTransform.runRoot$(RootTreeTransform.scala:14)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.runRoot(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.RootTreeTransform.runRoot(RootTreeTransform.scala:58)
[error]         at cps.macros.forest.RootTreeTransform.runRoot$(RootTreeTransform.scala:14)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.runRoot(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.RootTreeTransform.runRoot(RootTreeTransform.scala:58)
[error]         at cps.macros.forest.RootTreeTransform.runRoot$(RootTreeTransform.scala:14)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.runRoot(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.InlinedTreeTransform.runInlined(InlinedTreeTransform.scala:234)
[error]         at cps.macros.forest.InlinedTreeTransform.runInlined$(InlinedTreeTransform.scala:14)
[error]         at cps.macros.forest.RootTreeTransform$$anon$2.runInlined(RootTreeTransform.scala:168)
[error]         at cps.macros.forest.RootTreeTransform.$anonfun$3(RootTreeTransform.scala:52)
[error]         at cps.macros.forest.RootTreeTransform$B2$.inNestedContext(RootTreeTransform.scala:161)
[error]         at cps.macros.forest.RootTreeTransform.runRoot(RootTreeTransform.scala:53)
[error]         at cps.macros.forest.RootTreeTransform.runRoot$(RootTreeTransform.scala:14)
[error]         at cps.macros.forest.InlinedTreeTransform$Bridge$1.runRoot(InlinedTreeTransform.scala:273)
[error]         at cps.macros.forest.RootTreeTransform.runRoot(RootTreeTransform.scala:58)
[error]         at cps.macros.forest.RootTreeTransform.runRoot$(RootTreeTransform.scala:14)
[error]         at cps.macros.forest.InlinedTreeTransform$Bridge$1.runRoot(InlinedTreeTransform.scala:273)
[error]         at cps.macros.forest.InlinedTreeTransform.runInlined(InlinedTreeTransform.scala:234)
[error]         at cps.macros.forest.InlinedTreeTransform.runInlined$(InlinedTreeTransform.scala:14)
[error]         at cps.macros.forest.InlinedTreeTransform$Bridge$1.runInlined(InlinedTreeTransform.scala:273)
[error]         at cps.macros.forest.InlinedTreeTransform$Bridge$1.bridge(InlinedTreeTransform.scala:283)
[error]         at cps.macros.forest.InlinedTreeTransform$.run(InlinedTreeTransform.scala:287)
[error]         at cps.macros.Async$.rootTransform(Async.scala:272)
[error]         at cps.macros.Async$.$anonfun$1(Async.scala:116)
[error]         at cps.macros.misc.WithOptExprProxy$.apply(WithOptExprProxy.scala:26)
[error]         at cps.macros.Async$.transformMonad(Async.scala:139)
[error]         at cps.macros.Async$.transformImpl(Async.scala:64)
[error]         at cps.macros.Async$.transformNotInlined$1(Async.scala:321)
[error]         at cps.macros.Async$.$anonfun$7(Async.scala:328)
[error]         at cps.macros.Async$.inInlined$1(Async.scala:302)
[error]         at cps.macros.Async$.transformContextLambdaImpl(Async.scala:328)
[error] 
Error compiling project (Scala 3.2.1, JVM)
Compilation failed
```

**Comment by mushtaq** [comment]
@armanbilge This compiles:

```scala
//> using lib "com.github.rssh::shim-scala-async-dotty-cps-async::0.9.12"

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global
import async.Async.*

def futureFetchList[A](l: List[Future[A]]): Future[List[A]] =
  async {
    l.map(await(_))
  }
```
